/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRideRouteImport } from './routes/post-ride'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FindRidesRouteImport } from './routes/find-rides'
import { Route as IndexRouteImport } from './routes/index'

const PostRideRoute = PostRideRouteImport.update({
  id: '/post-ride',
  path: '/post-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRidesRoute = FindRidesRouteImport.update({
  id: '/find-rides',
  path: '/find-rides',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-rides': typeof FindRidesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/post-ride': typeof PostRideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-rides': typeof FindRidesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/post-ride': typeof PostRideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-rides': typeof FindRidesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/post-ride': typeof PostRideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-rides' | '/how-it-works' | '/post-ride'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-rides' | '/how-it-works' | '/post-ride'
  id: '__root__' | '/' | '/find-rides' | '/how-it-works' | '/post-ride'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindRidesRoute: typeof FindRidesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PostRideRoute: typeof PostRideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post-ride': {
      id: '/post-ride'
      path: '/post-ride'
      fullPath: '/post-ride'
      preLoaderRoute: typeof PostRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-rides': {
      id: '/find-rides'
      path: '/find-rides'
      fullPath: '/find-rides'
      preLoaderRoute: typeof FindRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindRidesRoute: FindRidesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PostRideRoute: PostRideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
